# Generated by Django 4.2.20 on 2025-03-16 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="customuser", options={"managed": False},),
    ]
