# Generated by Django 4.2.20 on 2025-03-17 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_create_guest_users"),
    ]

    operations = [
        migrations.RemoveField(model_name="customuser", name="profile_photo_url",),
        migrations.AddField(
            model_name="customuser",
            name="profile_photo_data",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
