# Generated by Django 4.2.20 on 2025-03-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Closet",
            fields=[
                ("closet_id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={"db_table": "Closet", "managed": False,},
        ),
        migrations.CreateModel(
            name="ClothingItem",
            fields=[
                ("item_id", models.AutoField(primary_key=True, serialize=False)),
                ("item_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("category_id", models.IntegerField(blank=True, null=True)),
                ("color", models.CharField(blank=True, max_length=50, null=True)),
                ("brand", models.CharField(blank=True, max_length=100, null=True)),
                ("image_url", models.BinaryField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"db_table": "ClothingItems", "managed": True,},
        ),
        migrations.CreateModel(
            name="Subcategories",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
            options={"db_table": "Categories",},
        ),
    ]
