# Generated by Django 4.2.20 on 2025-03-09 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClothingItem",
            fields=[
                ("item_id", models.AutoField(primary_key=True, serialize=False)),
                ("item_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("subcategory_id", models.IntegerField(blank=True, null=True)),
                ("color", models.CharField(blank=True, max_length=50, null=True)),
                ("brand", models.CharField(blank=True, max_length=100, null=True)),
                ("image_url", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"db_table": "ClothingItems",},
        ),
        migrations.CreateModel(
            name="Closet",
            fields=[
                ("closet_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="closet.clothingitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "Closet",},
        ),
    ]
