# Generated by Django 4.2.20 on 2025-03-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("closet", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="clothingitem", name="image_url",),
        migrations.AddField(
            model_name="clothingitem",
            name="image_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
