# Generated by Django 4.2.20 on 2025-03-09 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("closet", "0002_alter_clothingitem_options"),
    ]

    operations = [
        migrations.AlterModelOptions(name="closet", options={"managed": False},),
    ]
