# Generated by Django 5.1.7 on 2025-03-17 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0002_remove_clothingitem_image_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothingitem',
            old_name='image_path',
            new_name='image_url',
        ),
    ]
