# Generated by Django 5.1.5 on 2025-03-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("closet", "0003_alter_closet_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subcategories",
            fields=[
                ("subcategory_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "Subcategories",
            },
        ),
    ]
